### PR TITLE
Add display_version to antora.yml

### PR DESCRIPTION
**Pull request by nvitucci**

### CODE REVIEW

**Review by recrwplay — APPROVED** [review]

**Review by FlorentinD — APPROVED** [review]
Looks cleaner :)

We can get rid of the neo4j versions here?

**Comment by nvitucci** [comment]
> Looks cleaner :)
> 
> We can get rid of the neo4j versions here?

I haven't seen any usage for those here. Do you know why were they added in the first place? Are you using them in the main GDS docs?

**Comment by FlorentinD** [comment]
yes we do have them in the main docs. Although with the same outdated values.
```
    neo4j-version: '4.1'
    neo4j-version-exact: '4.1.1'
    neo4j-buildnumber: '4.1'
```
So we can remove them there too?

**Comment by nvitucci** [comment]
> yes we do have them in the main docs. Although with the same outdated values.
> 
> ```
>     neo4j-version: '4.1'
>     neo4j-version-exact: '4.1.1'
>     neo4j-buildnumber: '4.1'
> ```
> 
> So we can remove them there too?

I guess so. Just make sure by running a search before and building the docs after removing them.

**Pull request merged**
