### PR TITLE
Update endpoint docs for de-tiered algos

### PR DESCRIPTION
**Pull request by jjaderberg**
- Add untiered Kmeans endpoint docs
- Add untiered Harmonic Centrality endpoint docs

Thank you for your contribution to the Graph Data Science Client project.

Before submitting this PR, please read [Contributing to the Neo4j Ecosystem](https://github.com/neo4j/graph-data-science-client/blob/main/CONTRIBUTING.md). 

Make sure:
- [ ] You signed the [Neo4j CLA](https://neo4j.com/developer/cla/#sign-cla) (Contributor License Agreement) so that we are allowed to ship your code in our library
- [ ] Your contribution is covered by tests

### CODE REVIEW

**Comment by jjaderberg** [comment]
[Kmeans](https://trello.com/c/3Iv3uw0J/8543-kmeans)

**Review by FlorentinD — APPROVED** [review]
I thinks these look good.

I would only suggest to add a deprecation note in the docs such as done for scaleProperties

```
.. deprecated:: 2.4.0
Since GDS server version 2.4.0 you should use the endpoint :func:`gds.scaleProperties.mutate` instead.
```

**Comment by jjaderberg** [comment]
@FlorentinD added deprecation notes, does that look correct to you?

**Review by FlorentinD — APPROVED** [review]

**Comment by FlorentinD** [comment]
with all these renames coming at once, its likely this PR wont go green as #451 will do the rest. So need to check the CI failure

**Pull request merged**
